force-app/main/default/objects/Customer_Portfolio__c/Customer_Portfolio__c.object-meta.xml
<CustomObject>
    <label>Customer Portfolio</label>
    <nameField>
        <displayFormat>CustomerPortfolio-{00000}</displayFormat>
        <label>Customer Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Portfolio__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Portfolios</relationshipLabel>
    <relationshipName>Customer_Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Portfolio__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Portfolios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerPortfolioTriggerHelper.cls
/**
 * CustomerPortfolioTriggerHelper handles dml operations logics on Customer_Portfolio__c SObject
 * 
 * Author: Rafael Barbaroto
 * Created: 26th June 2024
 */
public without sharing class CustomerPortfolioTriggerHelper {
    
    /**
     * Generates external ID for a given Customer_Portfolio__c record
     *
     * @param  customerPortfolio - Customer_Portfolio__c record
     * @return  String
    */
    public static String generateExternalId(Customer_Portfolio__c customerPortfolio)
    {
 return '';
        // RB: use this method if extra logic is required
    }

    /**
     * Generates external IDs given a list of Customer_Portfolio__c records
     * To be used on BEFORE INSERT DML
     *
     * @param  customerPortfolios - List of new Customer_Portfolio__c records
     * @return  void
    */
    public static void generateExternalIds(List<Customer_Portfolio__c> customerPortfolios)
    {
        for(Customer_Portfolio__c portfolio : customerPortfolios)
        {
            portfolio.External_Id__c = generateExternalId(portfolio);
        }
    }

    /**
     * Returns a list of Customer_Portfolio__c records in which
     * the source is set to 'External'
     *
     * @param  customerPortfolios - List of Customer_Portfolio__c that is to be filtered
     * @return  filtered list of Customer_Portfolio__c records
    */
    public static List<Customer_Portfolio__c> filterByExternalPortfolios(List<Customer_Portfolio__c> customerPortfolios)
    {
        List<Customer_Portfolio__c> filteredList = new List<Customer_Portfolio__c>();
        for(Customer_Portfolio__c portfolio : customerPortfolios)
        {
            if(portfolio.Source__c == 'External')
            {
                filteredList.add(portfolio);
            }
        }

        return filteredList;
    }

    /**
     * Inserts ContactShare records for controlling access
     *
     * @param  customerPortfolios - List of updated Customer_Portfolio__c records
     * @return void
    */
    public static void shareCustomers(List<Customer_Portfolio__c> customerPorfolios)
    {
        List<ContactShare> newContactShares = new List<ContactShare>();

        for(Customer_Portfolio__c customerPorfolio : customerPorfolios)
        {
            newContactShares.add(createContactShareFromCustomerPorfolio(customerPorfolio));
        }

        Database.insert(newContactShares, false);
    }

    /**
     * Creates ContactShare records for controlling access
     *
     * @param  customerPortfolios - List of updated Customer_Portfolio__c records
     * @return void
    */
    public static ContactShare createContactShareFromCustomerPorfolio(Customer_Portfolio__c customerPortfolio)
    {
        ContactShare newContactShare = new ContactShare();
        newContactShare.UserOrGroupId = customerPortfolio.User__c;
        newContactShare.ContactId = customerPortfolio.Contact__c;
        newContactShare.ContactAccessLevel = 'Read';
        newContactShare.RowCause = 'Manual';

        return newContactShare;
    }

    /**
     * Recalculates 
     *
     * @param  customerPortfolios - List of deleted Customer_Portfolio__c records
     * @return void
    */
    public static void recalculateContactSharing(List<Customer_Portfolio__c> customerPorfolios)
    {
        UserRole currentUserRole = [SELECT Id FROM UserRole WHERE Id =: System.userInfo.getUserRoleId()];
        Set<Id> contactIds = new Set<Id>();
        Set<Id> userIds = new Set<Id>();
        for(Customer_Portfolio__c customerPorfolio : customerPorfolios)
        {
            contactIds.add(customerPorfolio.Contact__c);
            userIds.add(customerPorfolio.User__c);
        }

        Database.delete([SELECT Id FROM ContactShare WHERE UserOrGroupId IN :userIDs AND ContactId IN :contactIds]);
    }
}